#!/bin/sh
#
# Run "make" in the correct build environment.

if ! ( docker image inspect arculator-build >/dev/null ) ; then
    docker build -t arculator-build . || exit 1
fi
docker run -u $(id -u):$(id -g) --rm -v $(pwd):/src arculator-build make $*
